version: '3.2'

services:
  db:
    image: postgres:11-alpine
    volumes:
    - pgdata:/var/lib/postgresql/data
    env_file:
    - gift_app/local.env

  gift_app:
    build: gift_app
    command: python -m gift_app.main
    entrypoint: sh /wait-for.sh db 5432
    env_file:
    - gift_app/local.env
    depends_on:
    - db

volumes:
  pgdata: {}
